site_name: Url Shorter
site_description: Its all about a Weissman score > 5.0
repo_url: https://github.com/Fr33dman/urlshorter
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/Fr33dman">Fr33dman</a>.
dev_addr: 127.0.0.1:8001
theme: readthedocs

nav:
  - Home: 'index.md'
  - API:
      - Url Shorter: 'api/shorter.md'
